;/*!modules/action/search.jsx*/
define("modules/action/search.jsx",function(e,c,s){"use strict";s.exports=Reflux.createActions(["changeSearch"])});
;/*!modules/action/type.jsx*/
define("modules/action/type.jsx",function(e,t,c){"use strict";c.exports=Reflux.createActions(["changeType"])});
;/*!modules/component/header.jsx*/
define("modules/component/header.jsx",function(e,t,a){"use strict";a.exports=React.createClass({displayName:"exports",getDefaultProps:function(){return{url:"img/logo.png",data:[{href:"#/type/movie",title:"视频"},{href:"#/type/games",title:"游戏"},{href:"#/type/news",title:"新闻"},{href:"#/type/sports",title:"体育"},{href:"#/type/buy",title:"购物"},{href:"#/type/friends",title:"社交"}]}},createList:function(e){return e.map(function(e,t){return React.createElement("li",{key:t},React.createElement("a",{href:e.href},e.title))})},goHome:function(){ReactRouter.hashHistory.replace("/")},gotoSearch:function(e){13===e.keyCode&&(ReactRouter.hashHistory.replace("/search/"+e.target.value),e.target.value="")},render:function(){return React.createElement("div",{className:"header"},React.createElement("div",{className:"container"},React.createElement("input",{type:"text",className:"pull-right",onKeyUp:this.gotoSearch,ref:"searchValue"}),React.createElement("img",{src:this.props.url,onClick:this.goHome,className:"pull-left"}),React.createElement("ul",{className:"nav nav-pills nav-justified"},this.createList(this.props.data))),React.createElement("div",{className:"banner banner-1"}))}})});
;/*!modules/app.jsx*/
define("modules/app.jsx",function(e,t,n){"use strict";var a=e("modules/component/header.jsx"),c=e("modules/action/search.jsx"),o=e("modules/action/type.jsx");n.exports=React.createClass({displayName:"exports",render:function(){return React.createElement("div",null,React.createElement(a,null),React.createElement("div",{className:"app-main container"},this.props.children))},checkRoute:function(){0===this.props.location.pathname.indexOf("/type/")?o.changeType(this.props.params.id):0===this.props.location.pathname.indexOf("/search/")&&c.changeSearch(this.props.params.query)},componentDidMount:function(){this.checkRoute()},componentDidUpdate:function(){this.checkRoute()}})});
;/*!modules/conf.jsx*/
define("modules/conf.jsx",function(e,s,n){"use strict";n.exports={BANNER_NUM:2,ITEM_NUM:33,DATABASE:[]}});
;/*!modules/tools/imageloader.jsx*/
define("modules/tools/imageloader.jsx",function(t,i,n){"use strict";var e=t("modules/conf.jsx").BANNER_NUM,s=t("modules/conf.jsx").ITEM_NUM,o=function(t,i,n){this.done=t,this.success=i,this.fail=n,this.init()};o.prototype={init:function(){this.bannerNum=e,this.itemNum=s,this.total=this.bannerNum+this.itemNum,this.loader()},loader:function(){for(var t=this.bannerNum,i=this.itemNum;--t>=0;)this.loadImage(this.getBannerUrl(t),!0);for(;--i>=0;)this.loadImage(this.getItemUrl(i),!1)},getBannerUrl:function(t){return"img/banner/banner"+t+".jpg"},getItemUrl:function(t){return"img/item/item"+t+".jpg"},dealNum:function(t){t?--this.bannerNum:--this.itemNum},checkDone:function(){0===this.itemNum&&0===this.bannerNum&&this.done(this.total)},loadImage:function(t,i){var n=new Image;n.onload=function(){this.dealNum(i),this.success(this.total,this.total-this.itemNum-this.bannerNum),this.checkDone()}.bind(this),n.onerror=function(){this.dealNum(i),this.fail(this.total,this.total-this.itemNum-this.bannerNum),this.checkDone()}.bind(this),n.src=t}},n.exports=o});
;/*!modules/mixins/render.jsx*/
define("modules/mixins/render.jsx",function(e,t,a){"use strict";var n=e("modules/conf.jsx").ITEM_NUM;a.exports={getBgImageUrl:function(){return"url(../img/item/item"+parseInt(Math.random()*n)+".jpg)"},createList:function(){return this.state.list.map(function(e,t){var a={backgroundImage:this.getBgImageUrl()};return React.createElement("li",{key:t,style:a},React.createElement("a",{href:e.site},React.createElement("div",{className:"content"},React.createElement("h2",null,e.name)),React.createElement("div",{className:"layer"},React.createElement("p",null,"公司：",e.company),React.createElement("p",null,"类型：",e.type),React.createElement("p",null,"描述：",e.description))))}.bind(this))}}});
;/*!modules/page/home.jsx*/
define("modules/page/home.jsx",function(e,t,s){"use strict";var a=e("modules/mixins/render.jsx"),n=e("modules/conf.jsx");s.exports=React.createClass({displayName:"exports",mixins:[a],getInitialState:function(){return{list:n.DATABASE}},render:function(){return React.createElement("div",{className:"inner"},React.createElement("ul",{className:"clearfix"},this.createList()))}})});
;/*!modules/store/search.jsx*/
define("modules/store/search.jsx",function(e,r,s){"use strict";var n=e("modules/action/search.jsx"),o=e("modules/conf.jsx");s.exports=Reflux.createStore({listenables:[n],onChangeSearch:function(e){var r=[];o.DATABASE.forEach(function(s){for(var n in s)if(s[n].indexOf(e)>=0)return void r.push(s)}),this.trigger(r)}})});
;/*!modules/page/search.jsx*/
define("modules/page/search.jsx",function(e,s,t){"use strict";var a=e("modules/mixins/render.jsx"),n=e("modules/conf.jsx"),r=e("modules/store/search.jsx");t.exports=React.createClass({displayName:"exports",mixins:[a,Reflux.connect(r,"list")],getInitialState:function(){return{list:n.DATABASE}},render:function(){return React.createElement("div",{className:"inner"},React.createElement("ul",{className:"clearfix"},this.createList()))}})});
;/*!modules/store/type.jsx*/
define("modules/store/type.jsx",function(e,t,s){"use strict";var o=e("modules/action/type.jsx"),n=e("modules/conf.jsx");s.exports=Reflux.createStore({listenables:[o],onChangeType:function(e){var t=[];n.DATABASE.forEach(function(s){s.type===e&&t.push(s)}),this.trigger(t)}})});
;/*!modules/page/type.jsx*/
define("modules/page/type.jsx",function(e,t,s){"use strict";var n=e("modules/mixins/render.jsx"),a=e("modules/conf.jsx"),i=e("modules/store/type.jsx");s.exports=React.createClass({displayName:"exports",mixins:[n,Reflux.connect(i,"list")],getInitialState:function(){return{list:a.DATABASE}},render:function(){return React.createElement("div",{className:"inner"},React.createElement("ul",{className:"clearfix"},this.createList()))}})});
;/*!modules/route/route.jsx*/
define("modules/route/route.jsx",function(e,t,a){"use strict";var c=e("modules/app.jsx"),o=e("modules/page/home.jsx"),r=e("modules/page/search.jsx"),n=e("modules/page/type.jsx"),u=ReactRouter.Router,R=ReactRouter.Route,m=ReactRouter.IndexRoute;a.exports=React.createElement(u,null,React.createElement(R,{path:"/",component:c},React.createElement(m,{component:o}),React.createElement(R,{path:"type/:id",component:n}),React.createElement(R,{path:"search/:query",component:r}),React.createElement(ReactRouter.Redirect,{path:"ickt",to:"/"})))});
;/*!modules/bootsrap.jsx*/
define("modules/bootsrap.jsx",function(t){"use strict";var e=t("modules/tools/imageloader.jsx"),o=t("modules/conf.jsx"),n=t("modules/route/route.jsx"),s=$(".loader-text span");new e(function(){s.html("100.00"),$.get("data/sites.json",function(t){t&&0===t.errno&&(o.DATABASE=t.data,ReactDOM.render(n,$("#app")[0]))})},function(t,e){s.html((e/t*100).toFixed(2))},function(t,e){s.html((e/t*100).toFixed(2))})});